const body=document.body,themeBtn=document.getElementById('themeBtn'),toast=document.getElementById('toast'),surprise=document.getElementById('surprise'),surpriseBtn=document.getElementById('surpriseBtn'),closeSurprise=document.getElementById('closeSurprise');
document.getElementById('year').textContent=new Date().getFullYear();
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
themeBtn.addEventListener('click',()=>{body.classList.toggle('dark');const dark=body.classList.contains('dark');themeBtn.textContent=dark?'🌙':'☀️';localStorage.setItem('ragi-theme',dark?'dark':'light')});
if(localStorage.getItem('ragi-theme')==='dark'){body.classList.add('dark');themeBtn.textContent='🌙'}
document.querySelectorAll('.mini-btn').forEach(button=>button.addEventListener('click',()=>showToast(button.dataset.message)));
function openSurprise(){surprise.classList.add('open');surprise.setAttribute('aria-hidden','false')};function closeSurpriseBox(){surprise.classList.remove('open');surprise.setAttribute('aria-hidden','true')}
surpriseBtn.addEventListener('click',openSurprise);closeSurprise.addEventListener('click',closeSurpriseBox);surprise.addEventListener('click',e=>{if(e.target===surprise)closeSurpriseBox()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSurpriseBox()});
let typed='';document.addEventListener('keydown',e=>{if(e.key.length!==1)return;typed=(typed+e.key.toLowerCase()).slice(-4);if(typed==='ragi'){showToast('✦ Secret message unlocked: keep creating! ♡');typed=''}});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.animate([{opacity:0,transform:'translateY(18px)'},{opacity:1,transform:'translateY(0)'}],{duration:550,easing:'cubic-bezier(.2,.8,.2,1)',fill:'forwards'});observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('[data-reveal]').forEach(card=>{card.style.opacity='0';observer.observe(card)});
